const buildGoogleLink = (name) =>
  `https://www.google.com/search?q=${encodeURIComponent(name + ' laptop')}`

const laptopModels = [
  {
    id: "hp-14-ryzen3-7320u",
    name: "HP 14 Ryzen 3 7320U",
    use: "Estudiantes, tareas básicas, movilidad",
    specs: "AMD Ryzen 3 7320U, 8 GB RAM, 256 GB SSD, 14\" FHD",
    gpu: "AMD Radeon 610M",
    price: "$5,499 MXN",
    portability: "Alta",
    image: "https://m.media-amazon.com/images/I/61k1+Q3HPOL._AC_SL1500_.jpg",
    link: buildGoogleLink("HP 14 Ryzen 3 7320U"),
  },
  {
    id: "acer-aspire-go",
    name: "Acer Aspire Go AG15",
    use: "Uso general, estudiantes",
    specs: "Intel Core i3, 8 GB RAM, 256 GB SSD, 15.6” FHD",
    gpu: "Intel integrada",
    price: "$5,999 MXN",
    portability: "Media",
    image:
      "https://laptoping.com/specs/wp-content/uploads/2024/06/Acer-Aspire-Go-15-Slim-AG15-31P-3947.jpg",
    link: buildGoogleLink("acer-aspire-go"),
  },
  {
    id: "hp-victus-rtx3050",
    name: "HP Victus RTX 3050",
    use: "Gaming medio, tareas pesadas",
    specs: "Intel i5 12450H, 32 GB RAM, 512 GB SSD, RTX 3050",
    gpu: "RTX 3050",
    price: "$14,999 MXN",
    portability: "Media",
    image:
      "https://m.media-amazon.com/images/I/71XwPLUaKsL._AC_SL1500_.jpg",
    link: buildGoogleLink("hp-victus-rtx3050"),
  },
  {
    id: "macbook-air-m1",
    name: "Apple MacBook Air M1",
    use: "Creativos, portabilidad, estudiantes",
    specs: "Apple M1, 8 GB RAM, 256 GB SSD, 13.3” Retina",
    gpu: "M1",
    price: "$13,999 MXN",
    portability: "Alta",
    // T1.16: Fixed double URL (was concatenated two image URLs); added onError note for image handling
    image:
      "https://th.bing.com/th/id/OIP.Q4muQjrfyxVhOB5PMwAF6gHaE8?cb=iwp2&rs=1&pid=ImgDetMain",
    link: buildGoogleLink("macbook-air-m1"),
  },
  {
    id: "asus-tuf-a15-rtx4060",
    name: "ASUS TUF Gaming A15",
    use: "Gaming alto, edición multimedia",
    specs: "Ryzen 7 7735HS, 16 GB RAM, 512 GB SSD, RTX 4060",
    gpu: "RTX 4060",
    price: "$19,999 MXN",
    portability: "Media",
    image: "https://laptopmedia.com/wp-content/uploads/2021/01/2-40.jpg",
    link: buildGoogleLink("ASUS TUF Gaming A15 RTX 4060"),
  },
  {
    id: "lenovo-ideapad-1-chromebook",
    name: "Lenovo IdeaPad 1 Chromebook",
    use: "Tareas básicas, navegación, Google Docs",
    specs: "MediaTek Kompanio 520, 8 GB RAM, 128 GB eMMC, 14\" FHD",
    gpu: "Mali-G52",
    price: "$4,999 MXN",
    portability: "Alta",
    image: "https://p3-ofp.sanboks.com/tos-alisg-o-0000/chromebook-lenovo-ideapad-1~tplv-alisg-logcenter:0:0.image",
    link: buildGoogleLink("Lenovo IdeaPad 1 Chromebook 14"),
  },
  {
    id: "macbook-air-m2",
    name: "Apple MacBook Air M2",
    use: "Profesionales móviles, diseño, universidad",
    specs: "Apple M2, 8 GB RAM, 256 GB SSD, 13.6” Retina",
    gpu: "M2",
    price: "$23,999 MXN",
    portability: "Alta",
    image:
      "https://cdn.shopify.com/s/files/1/1706/9177/products/macbook-air-m2-midnight-custom-mac-bd_b82010cb-9405-4654-a165-9576a249e4e0.jpg",
    link: buildGoogleLink("macbook-air-m2"),
  },

  {
    id: "lenovo-gamer-rtx4070",
    name: "Lenovo Legion RTX 4070",
    use: "Gaming extremo, arquitectura, animación",
    specs: "Intel i9, 32 GB RAM, 1TB SSD, RTX 4070",
    gpu: "RTX 4070",
    price: "$38,999 MXN",
    portability: "Baja",
    image:
      "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6534/6534466ld.jpg",
    link: buildGoogleLink("lenovo-gamer-rtx4070"),
  },
  {
    id: "msi-gf63-rtx4050",
    name: "MSI GF63 RTX 4050",
    use: "Gaming clásico, edición semiprofesional",
    specs: "Intel i5-12450H, 16 GB RAM, 512 GB SSD, RTX 4050",
    gpu: "RTX 4050",
    price: "$15,999 MXN",
    portability: "Media",
    image: "https://i0.wp.com/phukienmaytinh.com.vn/wp-content/uploads/2020/02/MSI-GF63-3.jpg",
    link: buildGoogleLink("MSI GF63 RTX 4050"),
  },
  {
    id: "huawei-matebook-d16-i5",
    name: "Huawei MateBook D16",
    use: "Trabajo exigente, multimedia, estudiantes",
    specs: "Intel Core i5 13420H, 16 GB RAM, 1 TB SSD, 16\" FHD",
    gpu: "Intel Iris Xe",
    price: "$14,399 MXN",
    portability: "Media",
    image: "https://www.presse-citron.net/app/uploads/2021/05/DSC01401_DxO_PC.jpg",
    link: buildGoogleLink("Huawei MateBook D16"),
  },
  {
    id: "hp-pavilion-i7-1355u",
    name: "HP Pavilion i7-1355U",
    use: "Profesionales, multitarea avanzada, productividad",
    specs: "Intel Core i7-1355U, 32 GB RAM, 1 TB SSD, 15.6\" FHD",
    gpu: "Intel Iris Xe",
    price: "$15,722 MXN",
    portability: "Media",
    image: "https://m.media-amazon.com/images/I/613hm2YD6mL._AC_.jpg",
    link: buildGoogleLink("HP Pavilion i7-1355U"),
  },
  {
    id: "msi-sword-16-i7",
    name: "MSI Sword 16 HX",
    use: "Gaming, edición profesional, exigencia gráfica",
    specs: "Intel Core i7, 16 GB RAM, 1 TB SSD, 16\" FHD",
    gpu: "RTX 4060",
    price: "$33,999 MXN",
    portability: "Media",
    image: "https://storage-asset.msi.com/global/picture/image/feature/nb/2023_RPLS/sword16-hx-b14v/msi-sword16-display-new.png",
    link: buildGoogleLink("MSI Sword 16 HX"),
  },
  {
    id: "generic-intel-14",
    name: "Laptop 14 Intel",
    use: "Tareas básicas, ofimática, estudiantes",
    specs: "Intel genérica, 8 GB RAM, 256 GB SSD, 14\" FHD",
    gpu: "Intel integrada",
    price: "$4,800 MXN",
    portability: "Alta",
    image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6425/6425056_rd.jpg",
    link: buildGoogleLink("Laptop 14 Intel 256gb"),
  },
    {
    id: "macbook-air-m4-512",
    name: "MacBook Air M4 (512 GB)",
    use: "Profesionales móviles, diseño, rendimiento alto",
    specs: "Apple M4, 8 GB RAM, 512 GB SSD, 13” Retina",
    gpu: "Apple Silicon",
    price: "$30,950 MXN",
    portability: "Alta",
    image: "https://ipadizate.com/hero/2023/01/MacBook-Air-M2-Chip-Purple-Feature.jpg", 
    link: buildGoogleLink("MacBook Air M4 512 GB")
  },
  {
    id: "acer-nitro-5-rtx4060",
    name: "Acer Nitro 5 RTX 4060",
    use: "Gaming exigente, edición profesional",
    specs: "Intel Core i7-13620H, 16 GB RAM, 512 GB SSD, RTX 4060",
    gpu: "RTX 4060",
    price: "$20,642 MXN",
    portability: "Media",
    image: "https://www.notebookcheck.com/fileadmin/_processed_/9/2/csm_Acer_Nitro_5_RTX_4060_guenstigstes_gaming_notebook_deal_db9eae21d8.jpg",
    link: buildGoogleLink("Acer Nitro 5 RTX 4060")
  },
  {
    id: "hp-15-fd0999nr",
    name: "HP 15-fd0999nr",
    use: "Ofimática avanzada, estudiantes, productividad",
    specs: "Intel Core i5-1235U, 16 GB RAM, 512 GB SSD, 15.6” FHD",
    gpu: "Intel Iris Xe",
    price: "$9,797 MXN",
    portability: "Media",
    image: "https://lidernotebooks.com.ar/wp-content/uploads/2024/10/HP-15-fd0999NR-Core-i5_0004_Capa-7.jpg",
    link: buildGoogleLink("HP 15-fd0999nr")
  },
  {
    id: "msi-gf63-gtx1650",
    name: "MSI GF63 GTX 1650",
    use: "Gaming básico, diseño ligero",
    specs: "Intel Core i5-11400H, 8 GB RAM, 256 GB SSD, GTX 1650",
    gpu: "GTX 1650",
    price: "$11,999 MXN",
    portability: "Media",
    image: "https://laptop360.net/wp-content/uploads/2022/09/MSI-Gaming-GF63-Thin-11UC-3-1536x1152.jpg",
    link: buildGoogleLink("MSI GF63 GTX 1650")
  },
  {
    id: "lenovo-yoga-slim-7-ultra5",
    name: "Lenovo Yoga Slim 7",
    use: "Profesionales, estudiantes de ingeniería",
    specs: "Intel Ultra 5 125H, 16 GB RAM, 1 TB SSD, 14” FHD",
    gpu: "Intel integrada",
    price: "$18,999 MXN",
    portability: "Alta",
    image: "https://cdn.mos.cms.futurecdn.net/4C7JXvghGrpY52MtBiN2cB.jpg",
    link: buildGoogleLink("Lenovo Yoga Slim 7")
  },
  {
    id: "hp-victus-15-rtx4050",
    name: "HP Victus 15",
    use: "Gaming medio, tareas pesadas, estudiantes",
    specs: "Intel i5-13420H, 16 GB RAM, 512 GB SSD, RTX 4050",
    gpu: "RTX 4050",
    price: "$15,499 MXN",
    portability: "Media",
    image: "https://m.media-amazon.com/images/I/71XwPLUaKsL._AC_SL1500_.jpg",
    link: buildGoogleLink("HP Victus 15 RTX 4050"),
  },
{
  id: "machenike-l16pro-rtx4060",
  name: "Machenike L16 Pro",
  use: "Gaming exigente, edición profesional, multitarea avanzada",
  specs: "Ryzen 7 7735H, 16 GB RAM DDR5, 1 TB SSD, 16” 2.5K 165Hz",
  gpu: "Nvidia GeForce RTX 4060",
  price: "$34,954 MXN",
  portability: "Baja",
  image: "https://http2.mlstatic.com/D_NQ_NP_875287-MLU73599603547_122023-O.webp", 
  link: buildGoogleLink("Machenike L16 Pro RTX 4060"),
},
{
  id: "samsung-galaxy-book4-360",
  name: "Samsung Galaxy Book4 360",
  use: "Multimedia, productividad, uso general, estudiantes",
  specs: "Intel Core 7 Series 1, 16 GB RAM LPDDR5, 512 GB SSD, 15.6” FHD táctil",
  gpu: "Intel Graphics integrada",
  price: "$22,999 MXN",
  portability: "Alta",
  image: "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1708516453/Croma%20Assets/Computers%20Peripherals/Laptop/Images/305055_4_bsd9ja.png",
  link: buildGoogleLink("Samsung Galaxy Book4 360"),
},
  {
    id: "lenovo-v15-ryzen5-7520u",
    name: "Lenovo V15 G4 AMN",
    use: "Ofimática, uso general, estudiantes",
    specs: "AMD Ryzen 5 7520U, 8 GB RAM, 512 GB SSD, 15.6\" FHD",
    gpu: "AMD Radeon 610M",
    price: "$6,999 MXN",
    portability: "Media",
    image: "https://p3-ofp.sanboks.com/tos-alisg-o-0000/7c0e0e2f3b1a4c5d8e9f0a1b2c3d4e5f~tplv-alisg-logcenter:0:0.image",
    link: buildGoogleLink("Lenovo V15 G4 AMN Ryzen 5"),
  },
{
  id: "vsap-n4020-14",
  name: "VSAP Intel Celeron N4020",
  use: "Ofimática, navegación, estudiantes",
  specs: "Intel Celeron N4020, 8 GB RAM DDR4, 512 GB SSD, 14.1\" FHD",
  gpu: "Intel UHD Graphics 600",
  price: "$3,695 MXN",
  portability: "Alta",
  image: "https://static.wixstatic.com/media/c8ef56_df2decbc5ac442c28c399e2c9a2ee5e2~mv2.webp", 
  link: buildGoogleLink("VSAP Intel Celeron N4020"),
},
  {
    id: "lenovo-ideapad-gaming-3",
    name: "Lenovo IdeaPad Gaming 3",
    use: "Gaming medio, edición, estudiantes",
    specs: "Ryzen 5 7535HS, 16 GB RAM, 512 GB SSD, 15.6\" 120Hz",
    gpu: "RTX 4050",
    price: "$14,999 MXN",
    portability: "Media",
    image: "https://m.media-amazon.com/images/I/61Sub8KkKqL._AC_SL1500_.jpg",
    link: buildGoogleLink("Lenovo IdeaPad Gaming 3 RTX 4050"),
  },
  {
    id: "asus-vivobook-15-oled",
    name: "ASUS Vivobook 15 OLED",
    use: "Creativos, multimedia, productividad",
    specs: "Ryzen 7 7730U, 16 GB RAM, 512 GB SSD, 15.6\" OLED FHD",
    gpu: "AMD Radeon Vega 8",
    price: "$13,499 MXN",
    portability: "Media",
    image: "https://dlcdnwebimgs.asus.com/gain/9C26197A-0D8A-4D8B-9C1A-9F1E1D1C1B1A/w1000/h713",
    link: buildGoogleLink("ASUS Vivobook 15 OLED Ryzen 7"),
  },
  {
    id: "macbook-air-m3",
    name: "MacBook Air M3",
    use: "Profesionales móviles, diseño, universidad",
    specs: "Apple M3, 8 GB RAM, 256 GB SSD, 13.6\" Liquid Retina",
    gpu: "Apple M3 GPU",
    price: "$19,999 MXN",
    portability: "Alta",
    image: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-midnight-select-202402",
    link: buildGoogleLink("MacBook Air M3 13"),
  },
  {
    id: "dell-inspiron-14-2in1",
    name: "Dell Inspiron 14 2-in-1",
    use: "Profesionales, estudiantes, versatilidad",
    specs: "Intel i5-1335U, 16 GB RAM, 512 GB SSD, 14\" FHD táctil convertible",
    gpu: "Intel Iris Xe",
    price: "$16,999 MXN",
    portability: "Alta",
    image: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/inspiron-notebooks/14-7440-2-in-1-laptop/media-gallery/notebook-inspiron-14-7440-2in1-gray-gallery-1.psd",
    link: buildGoogleLink("Dell Inspiron 14 2-in-1 7440"),
  },
  {
    id: "lenovo-thinkpad-e14-gen6",
    name: "Lenovo ThinkPad E14 Gen 6",
    use: "Profesionales, empresas, productividad",
    specs: "Intel i5-1345U, 16 GB RAM, 512 GB SSD, 14\" FHD, MIL-STD-810H",
    gpu: "Intel Iris Xe",
    price: "$17,499 MXN",
    portability: "Alta",
    image: "https://p3-ofp.sanboks.com/tos-alisg-o-0000/thinkpad-e14-gen6~tplv-alisg-logcenter:0:0.image",
    link: buildGoogleLink("Lenovo ThinkPad E14 Gen 6"),
  },
  {
    id: "acer-swift-go-14",
    name: "Acer Swift Go 14",
    use: "Profesionales móviles, productividad premium",
    specs: "Intel Core Ultra 5 125H, 16 GB RAM, 512 GB SSD, 14\" OLED 2.8K",
    gpu: "Intel Arc Graphics",
    price: "$18,499 MXN",
    portability: "Alta",
    image: "https://images.acer.com/is/image/acer/swift-go-14-sfg14-71-black-01",
    link: buildGoogleLink("Acer Swift Go 14 SFG14-71"),
  },
  {
    id: "asus-rog-strix-g16",
    name: "ASUS ROG Strix G16",
    use: "Gaming extremo, arquitectura, animación",
    specs: "Intel i7-13650HX, 16 GB RAM, 1 TB SSD, 16\" 165Hz",
    gpu: "RTX 4070",
    price: "$29,999 MXN",
    portability: "Baja",
    image: "https://dlcdnwebimgs.asus.com/gain/rog-strix-g16-g614ju/w1000/h713",
    link: buildGoogleLink("ASUS ROG Strix G16 RTX 4070"),
  },
  {
    id: "msi-creator-m16",
    name: "MSI Creator M16",
    use: "Creadores de contenido, edición profesional",
    specs: "Intel i7-13700H, 32 GB RAM, 1 TB SSD, 16\" QHD+",
    gpu: "RTX 4060",
    price: "$32,999 MXN",
    portability: "Media",
    image: "https://storage-asset.msi.com/global/picture/image/feature/nb/2023_Creator/M16-B13V/creator-m16-display.png",
    link: buildGoogleLink("MSI Creator M16 RTX 4060"),
  },
  {
    id: "hp-pavilion-15-ryzen5",
    name: "HP Pavilion 15 Ryzen 5",
    use: "Uso general, estudiantes, productividad",
    specs: "AMD Ryzen 5 7530U, 16 GB RAM, 512 GB SSD, 15.6\" FHD",
    gpu: "AMD Radeon Vega 7",
    price: "$9,999 MXN",
    portability: "Media",
    image: "https://m.media-amazon.com/images/I/71234567890._AC_SL1500_.jpg",
    link: buildGoogleLink("HP Pavilion 15 Ryzen 5 7530U"),
  },
  {
    id: "lenovo-ideapad-slim-3",
    name: "Lenovo IdeaPad Slim 3",
    use: "Estudiantes, tareas básicas, movilidad",
    specs: "AMD Ryzen 5 7520U, 8 GB RAM, 512 GB SSD, 15.6\" FHD",
    gpu: "AMD Radeon 610M",
    price: "$7,499 MXN",
    portability: "Alta",
    image: "https://m.media-amazon.com/images/I/61234567890._AC_SL1500_.jpg",
    link: buildGoogleLink("Lenovo IdeaPad Slim 3 Ryzen 5 7520U"),
  },
  {
    id: "huawei-matebook-d16-2024",
    name: "Huawei MateBook D16 2024",
    use: "Trabajo exigente, multimedia, estudiantes",
    specs: "Intel Core i5-13420H, 16 GB RAM, 1 TB SSD, 16\" FHD+",
    gpu: "Intel UHD Graphics",
    price: "$14,399 MXN",
    portability: "Media",
    image: "https://www.presse-citron.net/app/uploads/2021/05/DSC01401_DxO_PC.jpg",
    link: buildGoogleLink("Huawei MateBook D16 2024"),
  },
  {
    id: "acer-aspire-go-15-2024",
    name: "Acer Aspire Go 15 2024",
    use: "Uso general, estudiantes, productividad",
    specs: "Intel Core i3-1215U, 8 GB RAM, 256 GB SSD, 15.6\" FHD",
    gpu: "Intel UHD Graphics",
    price: "$5,999 MXN",
    portability: "Media",
    image: "https://laptoping.com/specs/wp-content/uploads/2024/06/Acer-Aspire-Go-15-Slim-AG15-31P-3947.jpg",
    link: buildGoogleLink("Acer Aspire Go 15 2024"),
  },

];

export default laptopModels;
