const buildGoogleLink = (name) =>
  `https://www.google.com/search?q=${encodeURIComponent(name + ' laptop')}`

const laptopModels = [
  {
    id: "hp-stream-14",
    name: "HP Stream 14",
    use: "Estudiantes básicos, movilidad",
    specs: "Intel Celeron N4120, 4 GB RAM, 64 GB SSD, 14” HD",
    gpu: "Intel integrada",
    price: "$4,199 MXN",
    portability: "Alta",
    image:
      "https://www.notebookcheck.net/fileadmin/Notebooks/HP/Stream_14-ax002ng/2.jpg",
    link: buildGoogleLink("HP Stream 14"),
  },
  {
    id: "acer-aspire-go",
    name: "Acer Aspire Go AG15",
    use: "Uso general, estudiantes",
    specs: "Intel Core i3, 8 GB RAM, 256 GB SSD, 15.6” FHD",
    gpu: "Intel integrada",
    price: "$5,999 MXN",
    portability: "Media",
    image:
      "https://laptoping.com/specs/wp-content/uploads/2024/06/Acer-Aspire-Go-15-Slim-AG15-31P-3947.jpg",
    link: buildGoogleLink("acer-aspire-go"),
  },
  {
    id: "hp-victus-rtx3050",
    name: "HP Victus RTX 3050",
    use: "Gaming medio, tareas pesadas",
    specs: "Intel i5 12450H, 32 GB RAM, 512 GB SSD, RTX 3050",
    gpu: "RTX 3050",
    price: "$14,999 MXN",
    portability: "Media",
    image:
      "https://m.media-amazon.com/images/I/71XwPLUaKsL._AC_SL1500_.jpg",
    link: buildGoogleLink("hp-victus-rtx3050"),
  },
  {
    id: "macbook-air-m1",
    name: "Apple MacBook Air M1",
    use: "Creativos, portabilidad, estudiantes",
    specs: "Apple M1, 8 GB RAM, 256 GB SSD, 13.3” Retina",
    gpu: "M1",
    price: "$13,999 MXN",
    portability: "Alta",
    image:
      "https://th.bing.com/th/id/OIP.Q4muQjrfyxVhOB5PMwAF6gHaE8?cb=iwp2&rs=1&pid=ImgDetMainhttps://thangpro.vn/uploads/source/laptop/macbook/mac-air-m1/img-7707.jpg",
    link: buildGoogleLink("macbook-air-m1"),
  },
  {
    id: "asus-tuf-a15",
    name: "ASUS TUF Gaming A15",
    use: "Gaming alto, edición multimedia",
    specs: "Ryzen 7, 8 GB RAM, 512 GB SSD, RTX 3050",
    gpu: "RTX 3050",
    price: "$16,339 MXN",
    portability: "Media",
    image:
      "https://laptopmedia.com/wp-content/uploads/2021/01/2-40.jpg",
    link: buildGoogleLink("asus-tuf-a15"),
  },
  {
    id: "lenovo-chromebook-3",
    name: "Lenovo Chromebook 3",
    use: "Tareas básicas, navegación, Google Docs",
    specs: "Intel Celeron N4020, 4 GB RAM, 64 GB eMMC, 14” HD",
    gpu: "Intel integrada",
    price: "$3,499 MXN",
    portability: "Alta",
    image:
      "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6447/6447138_sd.jpg",
    link: buildGoogleLink("lenovo-chromebook-3"),
  },
  {
    id: "macbook-air-m2",
    name: "Apple MacBook Air M2",
    use: "Profesionales móviles, diseño, universidad",
    specs: "Apple M2, 8 GB RAM, 256 GB SSD, 13.6” Retina",
    gpu: "M2",
    price: "$23,999 MXN",
    portability: "Alta",
    image:
      "https://cdn.shopify.com/s/files/1/1706/9177/products/macbook-air-m2-midnight-custom-mac-bd_b82010cb-9405-4654-a165-9576a249e4e0.jpg",
    link: buildGoogleLink("macbook-air-m2"),
  },

  {
    id: "lenovo-gamer-rtx4070",
    name: "Lenovo Legion RTX 4070",
    use: "Gaming extremo, arquitectura, animación",
    specs: "Intel i9, 32 GB RAM, 1TB SSD, RTX 4070",
    gpu: "RTX 4070",
    price: "$38,999 MXN",
    portability: "Baja",
    image:
      "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6534/6534466ld.jpg",
    link: buildGoogleLink("lenovo-gamer-rtx4070"),
  },
  {
    id: "msi-gamer-rtx2060",
    name: "MSI GF63 RTX 2060",
    use: "Gaming clásico, edición semiprofesional",
    specs: "Intel i5 10th Gen, 16 GB RAM, 512 GB SSD, RTX 2060",
    gpu: "RTX 2060",
    price: "$17,499 MXN",
    portability: "Media",
    image:
      "https://i0.wp.com/phukienmaytinh.com.vn/wp-content/uploads/2020/02/MSI-GF63-3.jpg",
    link: buildGoogleLink("msi-gamer-rtx2060"),
  },
  {
    id: "huawei-matebook-d16-i5",
    name: "Huawei MateBook D16",
    use: "Trabajo exigente, multimedia, estudiantes",
    specs: "Intel Core i5 13420H, 16 GB RAM, 1 TB SSD, 16\" FHD",
    gpu: "Intel Iris Xe",
    price: "$14,399 MXN",
    portability: "Media",
    image: "https://www.presse-citron.net/app/uploads/2021/05/DSC01401_DxO_PC.jpg",
    link: buildGoogleLink("Huawei MateBook D16"),
  },
  {
    id: "hp-pavilion-i7-1355u",
    name: "HP Pavilion i7-1355U",
    use: "Profesionales, multitarea avanzada, productividad",
    specs: "Intel Core i7-1355U, 32 GB RAM, 1 TB SSD, 15.6\" FHD",
    gpu: "Intel Iris Xe",
    price: "$15,722 MXN",
    portability: "Media",
    image: "https://m.media-amazon.com/images/I/613hm2YD6mL._AC_.jpg",
    link: buildGoogleLink("HP Pavilion i7-1355U"),
  },
  {
    id: "msi-sword-16-i7",
    name: "MSI Sword 16 HX",
    use: "Gaming, edición profesional, exigencia gráfica",
    specs: "Intel Core i7, 16 GB RAM, 1 TB SSD, 16\" FHD",
    gpu: "RTX 4060",
    price: "$33,999 MXN",
    portability: "Media",
    image: "https://storage-asset.msi.com/global/picture/image/feature/nb/2023_RPLS/sword16-hx-b14v/msi-sword16-display-new.png",
    link: buildGoogleLink("MSI Sword 16 HX"),
  },
  {
    id: "generic-intel-14",
    name: "Laptop 14 Intel",
    use: "Tareas básicas, ofimática, estudiantes",
    specs: "Intel genérica, 8 GB RAM, 256 GB SSD, 14\" FHD",
    gpu: "Intel integrada",
    price: "$4,800 MXN",
    portability: "Alta",
    image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6425/6425056_rd.jpg",
    link: buildGoogleLink("Laptop 14 Intel 256gb"),
  },
    {
    id: "macbook-air-m4-512",
    name: "MacBook Air M4 (512 GB)",
    use: "Profesionales móviles, diseño, rendimiento alto",
    specs: "Apple M4, 8 GB RAM, 512 GB SSD, 13” Retina",
    gpu: "Apple Silicon",
    price: "$30,950 MXN",
    portability: "Alta",
    image: "https://ipadizate.com/hero/2023/01/MacBook-Air-M2-Chip-Purple-Feature.jpg", 
    link: buildGoogleLink("MacBook Air M4 512 GB")
  },
  {
    id: "acer-nitro-5-rtx4060",
    name: "Acer Nitro 5 RTX 4060",
    use: "Gaming exigente, edición profesional",
    specs: "Intel Core i7-13620H, 16 GB RAM, 512 GB SSD, RTX 4060",
    gpu: "RTX 4060",
    price: "$20,642 MXN",
    portability: "Media",
    image: "https://www.notebookcheck.com/fileadmin/_processed_/9/2/csm_Acer_Nitro_5_RTX_4060_guenstigstes_gaming_notebook_deal_db9eae21d8.jpg",
    link: buildGoogleLink("Acer Nitro 5 RTX 4060")
  },
  {
    id: "hp-15-fd0999nr",
    name: "HP 15-fd0999nr",
    use: "Ofimática avanzada, estudiantes, productividad",
    specs: "Intel Core i5-1235U, 16 GB RAM, 512 GB SSD, 15.6” FHD",
    gpu: "Intel Iris Xe",
    price: "$9,797 MXN",
    portability: "Media",
    image: "https://lidernotebooks.com.ar/wp-content/uploads/2024/10/HP-15-fd0999NR-Core-i5_0004_Capa-7.jpg",
    link: buildGoogleLink("HP 15-fd0999nr")
  },
  {
    id: "msi-gf63-gtx1650",
    name: "MSI GF63 GTX 1650",
    use: "Gaming básico, diseño ligero",
    specs: "Intel Core i5-11400H, 8 GB RAM, 256 GB SSD, GTX 1650",
    gpu: "GTX 1650",
    price: "$11,999 MXN",
    portability: "Media",
    image: "https://laptop360.net/wp-content/uploads/2022/09/MSI-Gaming-GF63-Thin-11UC-3-1536x1152.jpg",
    link: buildGoogleLink("MSI GF63 GTX 1650")
  },
  {
    id: "lenovo-yoga-slim-7-ultra5",
    name: "Lenovo Yoga Slim 7",
    use: "Profesionales, estudiantes de ingeniería",
    specs: "Intel Ultra 5 125H, 16 GB RAM, 1 TB SSD, 14” FHD",
    gpu: "Intel integrada",
    price: "$18,999 MXN",
    portability: "Alta",
    image: "https://cdn.mos.cms.futurecdn.net/4C7JXvghGrpY52MtBiN2cB.jpg",
    link: buildGoogleLink("Lenovo Yoga Slim 7")
  },
  {
  id: "machcreator-15n-i7",
  name: "Laptop Machcreator 15N",
  use: "Multitarea, trabajo profesional, estudiantes avanzados",
  specs: "Intel Core i7 13620H, 16 GB RAM, 512 GB SSD, 15.6” FHD",
  gpu: "Intel UHD Graphics",
  price: "$14,553 MXN",
  portability: "Media",
  image: "https://global.machenike.com/cdn/shop/files/11_818b6222-59ce-4193-a68b-bbc8e043b8ef.jpg",
  link: buildGoogleLink("Laptop Machcreator 15N i7"),
},
{
  id: "machenike-l16pro-rtx4060",
  name: "Machenike L16 Pro",
  use: "Gaming exigente, edición profesional, multitarea avanzada",
  specs: "Ryzen 7 7735H, 16 GB RAM DDR5, 1 TB SSD, 16” 2.5K 165Hz",
  gpu: "Nvidia GeForce RTX 4060",
  price: "$34,954 MXN",
  portability: "Baja",
  image: "https://http2.mlstatic.com/D_NQ_NP_875287-MLU73599603547_122023-O.webp", 
  link: buildGoogleLink("Machenike L16 Pro RTX 4060"),
},
{
  id: "samsung-galaxy-book4-360",
  name: "Samsung Galaxy Book4 360",
  use: "Multimedia, productividad, uso general, estudiantes",
  specs: "Intel Core 7 Series 1, 16 GB RAM LPDDR5, 512 GB SSD, 15.6” FHD táctil",
  gpu: "Intel Graphics integrada",
  price: "$22,999 MXN",
  portability: "Alta",
  image: "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1708516453/Croma%20Assets/Computers%20Peripherals/Laptop/Images/305055_4_bsd9ja.png",
  link: buildGoogleLink("Samsung Galaxy Book4 360"),
},
{
  id: "topgro-n5-i3-mx230",
  name: "Topgro N5",
  use: "Ofimática, uso general, multimedia básica",
  specs: "Intel Core i3-1005G1, 16 GB RAM DDR4, 512 GB SSD, NVIDIA GeForce MX230, 15.6” FHD",
  gpu: "NVIDIA GeForce MX230 (2 GB GDDR5)",
  price: "$6,935 MXN",
  portability: "Media",
  image: "https://m.media-amazon.com/images/I/71gXrO3lsqL._AC_.jpg", 
  link: buildGoogleLink("Topgro N5 i3 MX230"),
},
{
  id: "vsap-n4020-14",
  name: "VSAP Intel Celeron N4020",
  use: "Ofimática, navegación, estudiantes",
  specs: "Intel Celeron N4020, 8 GB RAM DDR4, 512 GB SSD, 14.1\" FHD",
  gpu: "Intel UHD Graphics 600",
  price: "$3,695 MXN",
  portability: "Alta",
  image: "https://static.wixstatic.com/media/c8ef56_df2decbc5ac442c28c399e2c9a2ee5e2~mv2.webp", 
  link: buildGoogleLink("VSAP Intel Celeron N4020"),
},

];

export default laptopModels;
